# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu/xsub/val_data_joint.npy
  label_path: ./data/ntu/xsub/val_label.pkl
  debug: False

# model
model: model.model.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.nturgbd.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: [1]
test_batch_size: 100
weights: runs/ntu_cs_joint-47-33456.pt

work_dir: ./work_dir/ntu/xsub/joint_test
model_saved_name: ./runs/ntu_cs_joint_test
save_score: True